import { StyleSheet } from "react-native";
import Colors from "../../constants/Colors";

const home = StyleSheet.create({
  container: {
    backgroundColor: Colors.white,
    flex: 1,
    paddingHorizontal: "25%",
    paddingBottom: "20%",
  },

  textBox: {
    flexDirection: "column",
    alignItems: "flex-start",
    marginTop: "10%",
  },
  authText: {
    fontFamily: "PoppinsSemiBold",
    color: Colors.white,
    fontSize: 22,
  },
  formContainer: {
    gap: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  formText: {
    fontFamily: "PoppinsMedium",
    fontSize: 16,
    color: Colors.text,
    alignSelf: "stretch",
  },
  input: {
    color: Colors.text,
    width: 330,
    borderStyle: "solid",
    alignSelf: "center",
    height: 50,
    backgroundColor: Colors.inputBg,
    paddingLeft: 50,
    fontFamily: "PoppinsSemiBold",
    borderWidth: 1,
    borderRadius: 8,
    borderColor: Colors.inputBg,
  },
  input2: {
    color: Colors.text,
    width: 330,
    borderStyle: "solid",
    alignSelf: "stretch",
    height: 50,
    backgroundColor: Colors.inputBg,
    paddingLeft: 15,
    fontFamily: "PoppinsSemiBold",
    borderWidth: 1,
    borderRadius: 8,
    borderColor: Colors.inputBg,
    position: "relative",
  },
  secContainer: {
    marginTop: 10,
    gap: 22,
  },
  footer: {
    textAlign: "center",
    color: Colors.text,
    fontFamily: "PoppinsRegular",
    fontSize: 14,
    marginVertical: 20,
  },
  error: {
    color: Colors.error,
    marginBottom: 10,
    fontSize: 13,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 4,
    marginRight: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  checked: {
    backgroundColor: Colors.primary,
  },
  checkmark: {
    color: Colors.white,
    fontWeight: "bold",
  },
  label: {
    fontSize: 16,
  },
  signupButtons: {
    height: 50,
    width: 50,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 100,
    borderColor: "#0000004D",
    borderWidth: 1,
    borderStyle: "solid",
    backgroundColor: Colors.white,
  },
  icon: {
    position: "absolute",
    top: 10,
    left: 10,
  },
  destinationField: {
    marginHorizontal: "8%",
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderRadius: 15,
    backgroundColor: Colors.white,
    position: "relative",
    top: "-6%",
    zIndex: 2,
    gap: 20,
    justifyContent: "center",
    alignItems: "center",
    width: "90%",
    alignSelf: "center",
    left: 0,
  },
  itemText: {
    color: Colors.text,
    fontFamily: "PoppinsMedium",
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: -0.32,
  },
  locationText: {
    color: Colors.text,
    fontFamily: "PoppinsSemiBold",
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: -0.4,
  },
  detailsIcon: {
    backgroundColor: "#00A1BF26",
    paddingVertical: 5,
    paddingHorizontal: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 10,
  },
  detailsText: {
    color: Colors.primary,
    fontFamily: "PoppinsMedium",
    fontSize: 14,
  },
  detailTitle: {
    paddingHorizontal: 10,
    color: Colors.text,
    fontFamily: "PoppinsSemiBold",
    fontSize: 16,
    letterSpacing: -0.32,
    fontWeight: 600,
  },
  details: {
    backgroundColor: Colors.white,
    marginHorizontal: 20,
    paddingVertical: 20,
    marginVertical: 20,
    borderRadius: 15,
  },
  terminalText: {
    color:Colors.text,
    fontFamily: 'PoppinsMedium',
    fontSize:16,
    letterSpacing: -0.32,
    fontWeight:600
  }, 
  terminalText2: {
    color:Colors.text,
    fontFamily: 'PoppinsRegular',
    fontSize:14,
    letterSpacing: -0.28,
    fontWeight:400
  }
});

export default home;
