const transportCompanies = [
  {
    id: 1,
    image: require("../../assets/images/transport1.png"),
    destination: "Lagos - Portharcourt",
    maxPassengers: 45,
    passengers: 2,
    time: '7am',
    price: "NGN 47,500",
    availability: "Available",
    availableSeats: 12,
    location1: 'Rumuola Park',
    location2: 'Lagos Station',
    from1: 'Portharcourt',
    from2: 'Lagos',
    date: '13/05/2025',
    vehicle: '18 Seater Bus',
    phone: '08055091820',
    terminal1: {
      name: 'Rumuola Terminal',
      address: 'No 233 Aba Road, Opposite Bori Camp Military Barracks, Rumola, Port-Harcourt',
      phone: '08055091820',
    },
    terminal2: {
      name: 'Oilmill Terminal',
      address: 'No 32B Aba Road, Oil Mill, By Eleme Junction, Beside Zenith Bank, OilMill, PH',
      phone: '0913 831 5658',
    },
    terminal3: {
      name: 'Rumuodumanya Terminal',
      address: '1 Airport Road, Rumuodumaya, PH',
      phone: '07055792624',
    }
  },
  {
    id: 2,
    image: require("../../assets/images/transport2.png"),
    destination: "Lagos - Portharcourt",
    maxPassengers: 8,
    passengers: 2,
    price: "NGN 60,000",
    time: '6:30am',
    availability: "Available",
    availableSeats: 12,
    location1: 'Rumuola Park',
    location2: 'Lagos Station',
    from1: 'Portharcourt',
    from2: 'Lagos',
    date: '13/05/2025',
    vehicle: '18 Seater Bus',
    phone: '08055091820',
    terminal1: {
      name: 'Rumuola Terminal',
      address: 'No 233 Aba Road, Opposite Bori Camp Military Barracks, Rumola, Port-Harcourt',
      phone: '08055091820',
    },
    terminal2: {
      name: 'Oilmill Terminal',
      address: 'No 32B Aba Road, Oil Mill, By Eleme Junction, Beside Zenith Bank, OilMill, PH',
      phone: '0913 831 5658',
    },
    terminal3: {
      name: 'Rumuodumanya Terminal',
      address: '1 Airport Road, Rumuodumaya, PH',
      phone: '07055792624',
    }
  },
  {
    id: 3,
    image: require("../../assets/images/transport3.png"),
    destination: "Lagos - Portharcourt",
    maxPassengers: 35,
    passengers: 2,
    price: "NGN 57,900",
    time: '6:30am',
    availability: "Available",
    availableSeats: 12,
    location1: 'Rumuola Park',
    location2: 'Lagos Station',
    from1: 'Portharcourt',
    from2: 'Lagos',
    date: '13/05/2025',
    vehicle: '18 Seater Bus',
    phone: '08055091820',
    terminal1: {
      name: 'Rumuola Terminal',
      address: 'No 233 Aba Road, Opposite Bori Camp Military Barracks, Rumola, Port-Harcourt',
      phone: '08055091820',
    },
    terminal2: {
      name: 'Oilmill Terminal',
      address: 'No 32B Aba Road, Oil Mill, By Eleme Junction, Beside Zenith Bank, OilMill, PH',
      phone: '0913 831 5658',
    },
    terminal3: {
      name: 'Rumuodumanya Terminal',
      address: '1 Airport Road, Rumuodumaya, PH',
      phone: '07055792624',
    }
  },
  {
    id: 4,
    image: require("../../assets/images/transport4.png"),
    destination: "Lagos - Portharcourt",
    maxPassengers: 4,
    passengers: 2,
    price: "NGN 57,900",
    time: '7am',
    availability: "Available",
    availableSeats: 12,
    location1: 'Rumuola Park',
    location2: 'Lagos Station',
    from1: 'Portharcourt',
    from2: 'Lagos',
    date: '13/05/2025',
    vehicle: '18 Seater Bus',
    phone: '08055091820',
    terminal1: {
      name: 'Rumuola Terminal',
      address: 'No 233 Aba Road, Opposite Bori Camp Military Barracks, Rumola, Port-Harcourt',
      phone: '08055091820',
    },
    terminal2: {
      name: 'Oilmill Terminal',
      address: 'No 32B Aba Road, Oil Mill, By Eleme Junction, Beside Zenith Bank, OilMill, PH',
      phone: '0913 831 5658',
    },
    terminal3: {
      name: 'Rumuodumanya Terminal',
      address: '1 Airport Road, Rumuodumaya, PH',
      phone: '07055792624',
    }
  },
  {
    id: 5,
    image: require("../../assets/images/transport5.png"),
    destination: "Lagos - Portharcourt",
    maxPassengers: 4,
    passengers: 2,
    price: "NGN 57,900",
    time: '7am',
    availability: "Available",
    availableSeats: 12,
    location1: 'Rumuola Park',
    location2: 'Lagos Station',
    from1: 'Portharcourt',
    from2: 'Lagos',
    date: '13/05/2025',
    vehicle: '18 Seater Bus',
    phone: '08055091820',
    terminal1: {
      name: 'Rumuola Terminal',
      address: 'No 233 Aba Road, Opposite Bori Camp Military Barracks, Rumola, Port-Harcourt',
      phone: '08055091820',
    },
    terminal2: {
      name: 'Oilmill Terminal',
      address: 'No 32B Aba Road, Oil Mill, By Eleme Junction, Beside Zenith Bank, OilMill, PH',
      phone: '0913 831 5658',
    },
    terminal3: {
      name: 'Rumuodumanya Terminal',
      address: '1 Airport Road, Rumuodumaya, PH',
      phone: '07055792624',
    }
  },
  {
    id: 6,
    image: require("../../assets/images/transport1.png"),
    destination: "Lagos - Portharcourt",
    maxPassengers: 12,
    passengers: 2,
    price: "NGN 57,900",
    time: '7am',
    availability: "Available",
    availableSeats: 12,
    location1: 'Rumuola Park',
    location2: 'Lagos Station',
    from1: 'Portharcourt',
    from2: 'Lagos',
    date: '13/05/2025',
    vehicle: '18 Seater Bus',
    phone: '08055091820',
    terminal1: {
      name: 'Rumuola Terminal',
      address: 'No 233 Aba Road, Opposite Bori Camp Military Barracks, Rumola, Port-Harcourt',
      phone: '08055091820',
    },
    terminal2: {
      name: 'Oilmill Terminal',
      address: 'No 32B Aba Road, Oil Mill, By Eleme Junction, Beside Zenith Bank, OilMill, PH',
      phone: '0913 831 5658',
    },
    terminal3: {
      name: 'Rumuodumanya Terminal',
      address: '1 Airport Road, Rumuodumaya, PH',
      phone: '07055792624',
    }
  },
];

export default transportCompanies;
